version: "3.7"

services:
  test_db:
    image: postgres:12-alpine
    container_name: test_orm_db
    restart: always
    ports:
      - 5667:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-db
      POSTGRES_USER: postgres
      PGDATA: /tmp
    volumes:
      - ./db:/var/lib/postgresql/data
